### ISSUE TITLE
Software Citation Guidance Task Force

### ISSUE THREAD

**Issue by npch** [force11/force11-sciwg#56]
This task force has the goal of producing guidance for different stakeholders to interpret and implement the [Software Citation Principles](https://doi.org/10.7717/peerj-cs.86).

Tasks
- [ ] Decide which stakeholder groups to target first
- [ ] Gather volunteers to contribute
- [ ] Define a broad outline and philosophy for guidance

**Comment by cm-j0nes** [comment]
I would like to volunteer for this - Catherine

**Comment by dbouquin** [comment]
Interested!

**Comment by mrchristian** [comment]
Hi I can help here from TIB / Generation R and relating these too Open Science MOOC and to learning resources

**Comment by ljhwang** [comment]
+1

**Comment by augustfly** [comment]
+1 (but I suspect I'll be on the publisher one too)

**Comment by mrchristian** [comment]
Contribute to research authors and for software makers

**Comment by jhausman** [comment]
I'm sure there will be some ESIP participation in this, producer and publisher

**Comment by katrinleinweber** [comment]
Over in https://github.com/force11/force11-sciwg/issues/48#issuecomment-372022915 we learned that BibLaTeX/biber supports 90% of the SCPs already. I wasn't in the June 5th meeting, I apologise, but I'd like to suggest that we more urgently need some pull/merge requests / patches against the style files of software-focussed journals. I'm guessing that those might have both the interest to distinguish software citations from papers, as well as authors who would particularly care about that.

I have the JSS TeX sources on my hard-drive for example, but I do not know how to adjust existing styles to actually render a software citation as for example Wolfram suggested: https://doi.org/10.5446/35357#t=16:15,16:41

His self-contained example worked fine :-) If someone wants to help adjust existing styles based on a dedicated software citation style, please let me know.

**Comment by ShelleyStall** [comment]
Please include me!

**Comment by danielskatz** [comment]
Also worth reading from @katrinleinweber: [Concrete Advice for FAIR Software](http://genr.eu/wp/concrete-advice-fair-software/)

**Comment by mrchristian** [comment]
And there is a video with @katrinleinweber posted at the bottom on the article, comparing and contrasting citation options https://av.tib.eu/series/415/the+leibniz+mathematical+modeling+and+simulation+mms+days+2018

**Comment by npch** [comment]
Hi All,

could you indicate in this Doodle which time is best for the first call for this task force?

https://doodle.com/poll/ra7k6igsv4eqgeps

**Comment by owlice** [comment]
I'm interested!

**Comment by paopao74cn** [comment]
+1

**Comment by Melissa37** [comment]
👍 I'd like to participate as a publisher stakeholder

**Comment by mingfangwu** [comment]
+1

**Comment by npch** [comment]
The time of our first call for the Software Citation Guidance Task Force will be at 16:00 UTC on Wednesday 28th November
Alternative timezones: https://www.timeanddate.com/worldclock/converter.html?iso=20181128T160000&p1=304&p2=tz_pt&p3=tz_ct&p4=tz_et&p5=tz_cet&p6=152

I'm going to try using Jitsi for the call:
- To join the video meeting, click this link: https://meet.jit.si/SoftwareCitationGuidanceGroupCall
- To join by phone, dial +1.512.402.2718 and enter this PIN: 2335688546#
- To view more phone numbers, click this link: https://meet.jit.si/static/dialInInfo.html?room=SoftwareCitationGuidanceGroupCall

Agenda and more details are here:
https://github.com/force11/force11-sciwg/blob/master/meetings/20181126-Guidance.md

@mingfangwu I've suggested an second regular timeslot as well - let me know if this works for you.

**Comment by npch** [comment]
Closing to clean-up issues. This guidance has now been completed in the form of checklists and published.

- [Software Citation Checklist for Developers](https://doi.org/10.5281/zenodo.3482768)
- [Software Citation Checklist for Authors](https://doi.org/10.5281/zenodo.3479198)
