### ISSUE TITLE
Citation files

### ISSUE THREAD

**Issue by danielskatz** [force11/force11-sciwg#64]
Based on discussion in Section 1 (and Section 3.3) of [A&P google doc](https://docs.google.com/document/d/1ze2Bh0pZXCy7_bHcC7CumQRmBAv8qP6reao4yU4JToY/edit?ts=5bb29c86#)

We have multiple types of citation files now: codemeta.json, citation.cff, CITATION files as proposed/used by CRAN.
* What guidance can we provide users, if any?
* Can we provide information on tools or methods for translation between these files?

**Comment by moranegg** [comment]
I agree with @katrinleinweber that 'translation tools' are out-of-scope.
The guidance on this subject should be to include one or more `metadata files` to  describe the content and to facilitate citation.

**Comment by danielskatz** [comment]
The writing group thinks we need to mention this topic, though maybe we don't need go into too much detail.

Perhaps add a table that says what these are, what the uses are (and links to them).

@cm-j0nes to suggest changes in 3.3 and maybe 1

**Comment by danielskatz** [comment]
closing this in favor of progress in the document itself.
