### ISSUE TITLE
Types of software

### ISSUE THREAD

**Issue by danielskatz** [force11/force11-sciwg#65]
Based on discussion in Section 2 of [A&P google doc](https://docs.google.com/document/d/1ze2Bh0pZXCy7_bHcC7CumQRmBAv8qP6reao4yU4JToY/edit?ts=5bb29c86#)

* We need to determine what scheme to use for the various software types.  Dan originally proposed a simple listing.  Alejandra proposed looking at various dimensions.
* We need to add other types that are not in the document now, such as services, executables, containers, packages or modules (that only work within a framework).
* Should this be a table?  Showing dimensions and values?  A drawing?

**Comment by danielskatz** [comment]
The writing group is struggling with how to express this as a drawing - the discussion will continue.  Help with a drawing would be welcome

**Comment by ljhwang** [comment]
What if software is considered in the context of workflow?  Do you wish to consider all of it as in scope?  When does it stop being a "tool" and becomes a "creative work"?

**Comment by danielskatz** [comment]
@dbouquin will be working on this drawing

**Comment by danielskatz** [comment]
Also we need to think about if we want to keep the [flowchart document[(https://docs.google.com/document/d/1et3R6IevQqQEDRRKsmIgi36HBWoIn-3ht4YUWGOV0eM/edit?ts=5bbe0f47#heading=h.r16j7ecdqpc3) separate or merge it together?  In either case, it is a somewhat different way of thinking about some of the same issues

**Comment by dbouquin** [comment]
Draft diagram [here](https://drive.google.com/file/d/1NQb05ekObGCgNo-igW6wxDhJFzrBCCX9/view?usp=sharing). Pretty wordy but it's a start at figuring this out I think.
![software_citation_2018](https://user-images.githubusercontent.com/5713878/49413842-350f5e00-f73f-11e8-8be9-1c49bed57e5b.png)

**Comment by dbouquin** [comment]
Refer to linked version (fixed a few mistakes)

**Comment by dbouquin** [comment]
Diagram files moved to [PR 87](https://github.com/force11/force11-sciwg/pull/87).

**Comment by dbouquin** [comment]
New draft - will insert into A&P doc ![draft_software_types_011419](https://user-images.githubusercontent.com/5713878/51161784-ceaf4c80-1861-11e9-8a13-6a49ab93f19e.png)

**Comment by danielskatz** [comment]
this discussion has been mostly resolved within the document now.
