### ISSUE TITLE
"Concept" language

### ISSUE THREAD

**Issue by danielskatz** [force11/force11-sciwg#67]
Based on discussion in Section 2 (and Section 3.2) of [A&P google doc](https://docs.google.com/document/d/1ze2Bh0pZXCy7_bHcC7CumQRmBAv8qP6reao4yU4JToY/edit?ts=5bb29c86#)

* Dan had suggested "concept" for the overall software package (not a particular version).
* Other names that have been suggested are "work" and "versionless" and “product” 
* What should we use?

**Comment by AlastairKelly** [comment]
I think "project" is another option.

**Comment by katrinleinweber** [comment]
+1 for `product`

**Comment by danielskatz** [comment]
An example from [another issue that has now been closed](#81), based on discussion with @AlastairKelly:

Microsoft Word is the project/work/product/concept/etc., and Microsoft Word 13 and Microsoft Word 16.0.1 are both versions.

**Comment by dbouquin** [comment]
I think "product" may be confusing to curators and muddy the water a bit in the context of proprietary software. I like "conceptual work" or concept for short still. @danielskatz pointed out that the intellectual content changes from version to version so both work and product seem to fall short of really nailing this. "Construct" might work?

**Comment by danielskatz** [comment]
I'm starting to think that there is no word that everyone will agree on.  I wonder if "software family" or something else new to this discussion would help?

**Comment by moranegg** [comment]
`software family` brings to mind a collection of different components, so different software artifacts and not just one software with several versions.

I can see that the proposition of `product` is ambiguous with commercial intentions.

In wikidata software type inherits from `creative work` and from `product`.
In schema.org SoftwareApplication and SoftwareSourceCode inherits from `creative work`.
In Datacite software is a type of `resource`  which can be used for the version and for the versionless artifact.
 
We can align with the [DOAP vocabulary](https://github.com/ewilderj/doap) with `project`.
This term is used by OpenHub, the [FSF directory](https://directory.fsf.org), [freshfoss](https://freshfoss.com/), [source forge](http://freshmeat.sourceforge.net/). 
Personally, i think it has a larger scope than all the versions of the same software, but it is a good compromise here.

I would prefer relying on a term used by a known software vocabulary and by software registries.
+1 for `project`

**Comment by danielskatz** [comment]
decision by writing group is on concept - @danielskatz will act on this, and also include some of @AlastairKelly 's point above in the text.

**Comment by danielskatz** [comment]
done - I think concept is now used everywhere, and I've tried to add discussion about this to Section 6.6
