### ISSUE TITLE
Non-developer identification of software

### ISSUE THREAD

**Issue by danielskatz** [force11/force11-sciwg#69]
Based on discussion in Section 3.1 and 3.2 and 3.3 and 3.5 of [A&P google doc](https://docs.google.com/document/d/1ze2Bh0pZXCy7_bHcC7CumQRmBAv8qP6reao4yU4JToY/edit?ts=5bb29c86#)

* For items like commercial software packages, how should they be identified?  This is a concern in the cases where the developer does not create an identifier.
* One option is to use RRIDs
  * https://www.force11.org/group/resource-identification-initiative
  * https://scicrunch.org/resources
* In 3.3, we need to know where to find metadata for such software.

**Comment by moranegg** [comment]
Non-developer is an ambiguous term, seems like you mean CSC (closed source concept) from the document.

I'm not familiar with RRIDs but it seems that the identifiers are limited to the research resources scope, correct me if it's not. If we need to identify commercial software it might not be registered in any research registry, or it might not cover all software.

Another option to consider for the concept/product/work level of the software are Wikidata identifiers. 

The joint RDA-FORCE11 working group about Software Source Code Identification, is a good place to push this subject.

**Comment by danielskatz** [comment]
I really meant how does identification work in a situation where the person who wants to cite the software is not the creator of the software, particularly when the software is not open source code.

**Comment by danielskatz** [comment]
closing this in favor of discussion and changes in the document
