### ISSUE TITLE
Transitive Credit

### ISSUE THREAD

**Issue by danielskatz** [force11/force11-sciwg#75]
Based on discussion in Section 3.7 (and 3.6) of [A&P google doc](https://docs.google.com/document/d/1ze2Bh0pZXCy7_bHcC7CumQRmBAv8qP6reao4yU4JToY/edit?ts=5bb29c86#)

* @mbjones suggested adding this subsection about transitive credit, and there are similar points made elsewhere, such as the last addition in 3.6
* Is this in scope?

**Comment by danielskatz** [comment]
I don't think this is in scope, and vote to remove it from the doc

**Comment by moranegg** [comment]
Transitive credit through dependencies is much more complex than described in the document and could be the subject of a task-force, especially to check feasibility with the existing systems in place.
In my opinion this a very difficult goal.

+1 for out-of-scope (#80)

**Comment by danielskatz** [comment]
will mark as out of scope - @danielskatz to add to "out of scope" discussion.  @dbouquin to mention credit somewhere else, and say that it's important, but out of scope for the time being.

**Comment by danielskatz** [comment]
done by @danielskatz  - when @dbouquin is satisfied she's done the other part, she should close this issue.

**Comment by danielskatz** [comment]
@dbouquin - just let me know when this should be close and I will close it

**Comment by dbouquin** [comment]
@danielskatz this looks good to me.
