### ISSUE TITLE
Institution items

### ISSUE THREAD

**Issue by danielskatz** [force11/force11-sciwg#79]
Based on discussion in Section 4.6 of [A&P google doc](https://docs.google.com/document/d/1ze2Bh0pZXCy7_bHcC7CumQRmBAv8qP6reao4yU4JToY/edit?ts=5bb29c86#)

* Need to address issues in this section.

**Comment by dbouquin** [comment]
Institutions also manage internal repositories - we can recommend that they incorporate software citation principles and metadata standards into their repository workflows and metadata schemas. We can also recommend promoting any guidelines the WG develops/training materials. Should we specifically focus at all on curators too? We talk about publishers but not repository curators who may want to make changes to their own repositories to better accommodate software citation/preservation.

**Comment by danielskatz** [comment]
I've added a note in 4.6 to indicate this possible repository role, pointing to the repository section: 4.3
