### ISSUE TITLE
Language for a series or line of software projects

### ISSUE THREAD

**Issue by AlastairKelly** [force11/force11-sciwg#81]
While we decide on a word for software projects/products/works/concepts (issue #67), it might also be helpful to simultaneously chose language to describe a series of software projects, as I anticipate this being needed at some point. So if Microsoft Word 16 and Microsoft Word 13 are projects, and Microsoft Word 16.0.1 is a version or release, what do we call Microsoft Word as it refers to any or all of the specific Word incarnations? My suggestions are a series or a line. 
When these terms are selected, I also think it would be useful to add to the paper a formal (but simple) concept model showing the relationships between these terms.

**Comment by danielskatz** [comment]
I think in the discussion we've, or at least the way I've been thinking, Microsoft Word is the project/work/product/concept/etc., and Microsoft Word 13 and Microsoft Word 16.0.1 are both version.  So I don't think we need another word.  If you agree, I wonder if we might close this issue and move some of this discussion to #67 and make that issue more clear.

**Comment by danielskatz** [comment]
closing and moving discussion to #67
